---
sidebar: sidebar
permalink: alerts-faq.html
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert
summary: This BlueXP alerts FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for BlueXP alerts
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== Access

*What's the BlueXP alerts URL?*
For the URL, in a browser, enter: https://console.bluexp.netapp.com/[https://console.bluexp.netapp.com/^] to access the BlueXP console. 

*Do you need a license to use BlueXP alerts?*

The BlueXP alerts service requires a NetApp ONTAP 9.10 or greater license. 

You do not need to have a trial license for this service.


*How do you enable BlueXP alerts?* 
BlueXP alerts does not require any enablement. The alerts option is automatically enabled on the BlueXP left navigation. 

To get going, you need to sign up or reach out to your NetApp Sales rep to try out this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the service.


**Does BlueXP alerts available in standard, restricted, and private modes?**
The service can be deployed in the BlueXP standard (public), restricted, and private modes. 

For an explanation about these modes across all BlueXP services, refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[BlueXP deployment modes^].

**How are access permissions handled?**
Only account admins have the ability to initiate the service and discover workloads (because this involves committing to usage of a resource). Subsequent interactions can be done by any role.

**What device resolution is best?**
The recommended device resolution for BlueXP alerts is 1920x1080 or better. 

**Which browser should I use?**
Any modern browser will work. 







