---
sidebar: sidebar
permalink: alerts-faq.html
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert
summary: This BlueXP alerts FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for BlueXP alerts
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== Access to BlueXP alerts

*What's the BlueXP alerts URL?*
For the URL, in a browser, enter: https://console.bluexp.netapp.com/[https://console.bluexp.netapp.com/^] to access the BlueXP console. 

*Do you need a license to use BlueXP alerts?*

The BlueXP alerts service requires a NetApp ONTAP 9.10 or greater license. The license does not need to be entered in BlueXP digital wallet. 

You do not need to have a trial license for this service.


*How do you enable BlueXP alerts?* 
BlueXP alerts does not require any enablement. The alerts option is automatically enabled on the BlueXP left navigation. 

To get going, when you use the BlueXP Connector, it will include the appropriate capabilities for the service.


**Does BlueXP alerts available in standard, restricted, and private modes?**
The service can be deployed in the BlueXP standard (public) only. 

For an explanation about these modes across all BlueXP services, refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[BlueXP deployment modes^].

**How are access permissions handled?**
Only BlueXP organization admins have the ability to initiate the BlueXP alerts service and discover workloads (because this involves committing to usage of a resource). 

Alerts are shown to logged in users depending on their access to the cluster's resource in that BlueXP organization. 

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html[Learn about BlueXP organizations].

== View alerts

**How long do I need to wait before I start getting alerts?**

Wait a maximum of 15 minutes for initial discovery and after that a maximum of 5 minutes for alerts to appear. This varies from alert to alert.

* *Why can't I see the alerts for ONTAP using direct mode without a BlueXP Connector?*

BlueXP alerts is available only using the on-premises standard BlueXP Connector. Using the direct mode does not monitor the clusters and does not display the alerts. 

**Why are some alerts disappearing from the Alerts list page?**

The alerting feature keeps some alerts in an Active state and closes them after either the counter condition is met or a time period is reached. This varies from alert to alert. 

To see all the alerts, select the Status column filter and select the Closed option.

== Display of information

**What device resolution is best?**
The recommended device resolution for BlueXP alerts is 1920x1080 or better. 

**Which browser should I use?**
Any modern browser will work. 






