---
sidebar: sidebar
permalink: alerts-start-prerequisites.html
keywords: what are bluexp alerts requirements, bluexp alerts, alerts prerequisites
summary: Get started with BlueXP alerts by verifying support for your environment, network access, login and web browser.
---

= BlueXP alerts prerequisites
:hardbreaks:
:icons: font
:imagesdir: ./media/get-started/

[.lead]
Get started with BlueXP alerts by verifying the readiness of your operational environment.

To use BlueXP alerts, you'll need these prerequisites: 


* ONTAP 9.10 and later. The on-premises working environment must be discovered in the BlueXP canvas.
** Cluster admin ONTAP permissions
+
For more licensing details, refer to link:concept-alerts.html[Learn about BlueXP alerts].


* In BlueXP: 

** A BlueXP working environment with NetApp on-premises NAS or SAN storage 
** A BlueXP Connector for an on-premises region must be set up in BlueXP. Refer to https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[BlueXP documentation to configure the Connector^].


** A BlueXP organization with at least one active Connector connecting to on-premises ONTAP clusters. All source and working environments must be in the same BlueXP organization. 
** A BlueXP user in that organization with Organization Admin privileges for discovering resources

** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html[Standard BlueXP requirements^]


