---
sidebar: sidebar
permalink: concept-alerts.html
keywords: netapp, ontap, alerts, capacity, performance,availability, security
summary: BlueXP alerts is a service that enables you to view issues or potential risks in your NetApp ONTAP environment related to capacity, performance, availability, and security. With the service, you can drill into details using NetApp System Manager.
---

= Learn about BlueXP alerts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP alerts is a service that enables you to view issues or potential risks in your NetApp ONTAP environment, for both on-premises and cloud environments. With the service, you can drill into details using NetApp System Manager.

//NOTE: THIS DOCUMENTATION IS PROVIDED AS A TECHNOLOGY PREVIEW.  With this preview offering, NetApp reserves the right to modify offering details, contents, and timeline before General Availability.   

== What you can do with BlueXP alerts 

The BlueXP alerts service helps you stay informed about risks or potential risk in your ONTAP storage environment. The BlueXP alerts service provides information about these severities and impact areas: 

* *Severities*: Critical, Error, Warning, Informational
* *Impact areas*: Capacity, Performance, Availability, Security, Configuration



== Benefits of using BlueXP alerts 

BlueXP alerts offers the following benefits: 

* Get alerts about your ONTAP storage across clusters.
* View alerts in the same BlueXP UI that you use for other services.
* Drill into alerts on ONTAP clusters -- start from BlueXP alerts and see details in NetApp System Manager. 


== Cost 

NetApp doesn’t charge you for using the trial version of BlueXP alerts. The full version of BlueXP alerts can be used with a NetApp ONTAP license.

== Licensing 

With BlueXP alerts, you can use different licensing plans including a free trial or bring your own ONTAP license.

The BlueXP alerts service requires a NetApp ONTAP 9.10 or greater license. 


For details, see link:alerts-start-licenses.html[Set up licensing].

== How BlueXP alerts works

At a high-level, BlueXP alerts works like this.

TBD

== Supported working environments and data sources

Use BlueXP alerts to check on issues in the following working environments and data sources:

//*Backup targets supported*

//* Amazon Web Services (AWS) S3
//* Microsoft Azure Blob
//* NetApp StorageGRID

*Working environments supported* 

* On-premises ONTAP NAS (using NFS and CIFS protocols)
* Cloud Volumes ONTAP for AWS (using NFS and CIFS protocols)
* Cloud Volumes ONTAP for Azure (using NFS and CIFS protocols)

NOTE: The following are not supported: FlexGroup volumes, ONTAP versions older than 9.11.1, iSCSI volumes, and Data protection (DP) volumes. 

*Data sources supported*

The service provides alerts regarding the following application-based workloads on primary data volumes:

* NetApp file shares
* VMware datastores
* Databases (MySQL and Oracle)



