settings:
  name: BlueXP alerts
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: bluexp-relnotes  
sidebar:
  entries:
    - title: BlueXP alerts docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new with BlueXP alerts
          url: /whats-new.html 
    - title: Get started
      entries:
        - title: Learn about BlueXP alerts
          url: /concept-alerts.html
        - title: Prerequisites
          url: /alerts-start-prerequisites.html
        - title: Quick start
          url: /alerts-start-quick-start.html
        - title: Set up BlueXP alerts 
          url: /alerts-start-setup.html
        - title: Access BlueXP alerts
          url: /alerts-start-login.html
    - title: Use BlueXP alerts
      entries:
        - title: Use BlueXP alerts overview
          url: /alerts-use-overview.html 
        - title: View potential risks in ONTAP storage
          url: /alerts-use-dashboard.html
        - title: View alerts in your storage environment
          url: /alerts-use-alerts.html
    - title: FAQ
      url: /alerts-faq.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family

