---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ontap, bluexp, system manager
summary: Learn what's new in BlueXP alerts.
---

= What's new with BlueXP alerts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP alerts.

// tag::whats-new[]

== 7 October 2024
This initial release of BlueXP alerts includes the following features:


* *BlueXP alerts list page*: You can quickly identify ONTAP clusters that have low capacity or low performance, gauge the extent of availability, and identify security risks. You can view alerts related to capacity, performance, protection, availability, security, and configuration. 

* *Alerts details*: You can drill into alert details and find recommendations. 

* *View cluster details linked to System Manager*: With BlueXP alerts, you can view alerts associated with your ONTAP storage environment and drill into the details that are linked to ONTAP System Manager.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html[Learn about BlueXP alerts].




// end::whats-new[] 

